//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesLibraryExercise.ConsoleApp.MoviesServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MovieData", Namespace="http://schemas.datacontract.org/2004/07/MoviesLibrary")]
    [System.SerializableAttribute()]
    public partial class MovieData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.List<string> _castField;
        
        private string _classificationField;
        
        private string _genreField;
        
        private int _movieIdField;
        
        private int _ratingField;
        
        private int _releaseDateField;
        
        private string _titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<string> _cast {
            get {
                return this._castField;
            }
            set {
                if ((object.ReferenceEquals(this._castField, value) != true)) {
                    this._castField = value;
                    this.RaisePropertyChanged("_cast");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _classification {
            get {
                return this._classificationField;
            }
            set {
                if ((object.ReferenceEquals(this._classificationField, value) != true)) {
                    this._classificationField = value;
                    this.RaisePropertyChanged("_classification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _genre {
            get {
                return this._genreField;
            }
            set {
                if ((object.ReferenceEquals(this._genreField, value) != true)) {
                    this._genreField = value;
                    this.RaisePropertyChanged("_genre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _movieId {
            get {
                return this._movieIdField;
            }
            set {
                if ((this._movieIdField.Equals(value) != true)) {
                    this._movieIdField = value;
                    this.RaisePropertyChanged("_movieId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _rating {
            get {
                return this._ratingField;
            }
            set {
                if ((this._ratingField.Equals(value) != true)) {
                    this._ratingField = value;
                    this.RaisePropertyChanged("_rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _releaseDate {
            get {
                return this._releaseDateField;
            }
            set {
                if ((this._releaseDateField.Equals(value) != true)) {
                    this._releaseDateField = value;
                    this.RaisePropertyChanged("_releaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _title {
            get {
                return this._titleField;
            }
            set {
                if ((object.ReferenceEquals(this._titleField, value) != true)) {
                    this._titleField = value;
                    this.RaisePropertyChanged("_title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MovieField", Namespace="http://schemas.datacontract.org/2004/07/MoviesLibraryExercise.ServiceLibrary")]
    public enum MovieField : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Classification = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Genre = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MovieId = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rating = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReleaseDate = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Title = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MoviesServiceReference.IMovieLibrary")]
    public interface IMovieLibrary {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieLibrary/GetMovies", ReplyAction="http://tempuri.org/IMovieLibrary/GetMoviesResponse")]
        System.Collections.Generic.List<MoviesLibraryExercise.ConsoleApp.MoviesServiceReference.MovieData> GetMovies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieLibrary/GetMovieById", ReplyAction="http://tempuri.org/IMovieLibrary/GetMovieByIdResponse")]
        MoviesLibraryExercise.ConsoleApp.MoviesServiceReference.MovieData GetMovieById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieLibrary/GetMoviesInOrder", ReplyAction="http://tempuri.org/IMovieLibrary/GetMoviesInOrderResponse")]
        System.Collections.Generic.List<MoviesLibraryExercise.ConsoleApp.MoviesServiceReference.MovieData> GetMoviesInOrder(MoviesLibraryExercise.ConsoleApp.MoviesServiceReference.MovieField field);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieLibrary/SearchMovies_Logic_1", ReplyAction="http://tempuri.org/IMovieLibrary/SearchMovies_Logic_1Response")]
        System.Collections.Generic.List<MoviesLibraryExercise.ConsoleApp.MoviesServiceReference.MovieData> SearchMovies_Logic_1(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieLibrary/SearchMovies_Logic_2", ReplyAction="http://tempuri.org/IMovieLibrary/SearchMovies_Logic_2Response")]
        System.Collections.Generic.List<MoviesLibraryExercise.ConsoleApp.MoviesServiceReference.MovieData> SearchMovies_Logic_2(string searchString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieLibrary/CreateMovie", ReplyAction="http://tempuri.org/IMovieLibrary/CreateMovieResponse")]
        int CreateMovie(MoviesLibraryExercise.ConsoleApp.MoviesServiceReference.MovieData movie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovieLibrary/UpdateMovie", ReplyAction="http://tempuri.org/IMovieLibrary/UpdateMovieResponse")]
        void UpdateMovie(MoviesLibraryExercise.ConsoleApp.MoviesServiceReference.MovieData movie);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMovieLibraryChannel : MoviesLibraryExercise.ConsoleApp.MoviesServiceReference.IMovieLibrary, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MovieLibraryClient : System.ServiceModel.ClientBase<MoviesLibraryExercise.ConsoleApp.MoviesServiceReference.IMovieLibrary>, MoviesLibraryExercise.ConsoleApp.MoviesServiceReference.IMovieLibrary {
        
        public MovieLibraryClient() {
        }
        
        public MovieLibraryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MovieLibraryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieLibraryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieLibraryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<MoviesLibraryExercise.ConsoleApp.MoviesServiceReference.MovieData> GetMovies() {
            return base.Channel.GetMovies();
        }
        
        public MoviesLibraryExercise.ConsoleApp.MoviesServiceReference.MovieData GetMovieById(int id) {
            return base.Channel.GetMovieById(id);
        }
        
        public System.Collections.Generic.List<MoviesLibraryExercise.ConsoleApp.MoviesServiceReference.MovieData> GetMoviesInOrder(MoviesLibraryExercise.ConsoleApp.MoviesServiceReference.MovieField field) {
            return base.Channel.GetMoviesInOrder(field);
        }
        
        public System.Collections.Generic.List<MoviesLibraryExercise.ConsoleApp.MoviesServiceReference.MovieData> SearchMovies_Logic_1(string searchString) {
            return base.Channel.SearchMovies_Logic_1(searchString);
        }
        
        public System.Collections.Generic.List<MoviesLibraryExercise.ConsoleApp.MoviesServiceReference.MovieData> SearchMovies_Logic_2(string searchString) {
            return base.Channel.SearchMovies_Logic_2(searchString);
        }
        
        public int CreateMovie(MoviesLibraryExercise.ConsoleApp.MoviesServiceReference.MovieData movie) {
            return base.Channel.CreateMovie(movie);
        }
        
        public void UpdateMovie(MoviesLibraryExercise.ConsoleApp.MoviesServiceReference.MovieData movie) {
            base.Channel.UpdateMovie(movie);
        }
    }
}
